
# Pandas function

In [6]:
import pandas as pd

csv_1=pd.read_csv("Country.csv")
print(csv_1)

    Unnamed: 0         Country  Population Country Code  \
0            0   United States   331002651           US
1            1           China  1439323776           CN
2            2           India  1380004385           IN
3            3          Brazil   212559417           BR
4            4        Pakistan   220892340           PK
5            5       Indonesia   273523615           ID
6            6         Nigeria   206139589           NG
7            7      Bangladesh   164689383           BD
8            8          Russia   145934462           RU
9            9          Mexico   128932753           MX
10          10           Japan   126476461           JP
11          11        Ethiopia   114963588           ET
12          12     Philippines   109581078           PH
13          13           Egypt   102334404           EG
14          14         Vietnam    97338579           VN
15          15        DR Congo    89561404           CD
16          16          Turkey    84339067           TR
17          17            Iran    83992949           IR
18          18         Germany    83783942           DE
19          19        Thailand    69799978           TH
20          20  United Kingdom    67886011           GB
21          21          France    65273511           FR
22          22           Italy    60461826           IT
23          23        Tanzania    59734218           TZ
24          24    South Africa    59308690           ZA
25          25         Myanmar    54409800           MM
26          26           Kenya    53771296           KE
27          27     South Korea    51269185           KR
28          28        Colombia    50882891           CO
29          29           Spain    46754778           ES
30          30          Uganda    45741007           UG
31          31       Argentina    45195774           AR
32          32         Algeria    43851044           DZ
33          33           Sudan    43849260           SD
34          34         Ukraine    43733762           UA
35          35            Iraq    40222493           IQ
36          36     Afghanistan    38928346           AF
37          37          Poland    37846611           PL
38          38          Canada    37742154           CA
39          39         Morocco    36910560           MA
40          40    Saudi Arabia    34813871           SA
41          41      Uzbekistan    33469203           UZ
42          42            Peru    32971854           PE
43          43          Angola    32866272           AO
44          44        Malaysia    32365999           MY
45          45      Mozambique    31255435           MZ
46          46           Ghana    31072940           GH
47          47           Yemen    29825968           YE
48          48           Nepal    29136808           NP

                                  National Anthem
0                        The Star-Spangled Banner
1                         March of the Volunteers
2                                  Jana Gana Mana
3                        Hino Nacional Brasileiro
4                           Pak Sarzamin Shad Bad
5                                  Indonesia Raya
6                            Arise, O Compatriots
7                              Amar Shonar Bangla
8          State Anthem of the Russian Federation
9                         Himno Nacional Mexicano
10                                       Kimigayo
11                            Ethiopia, Be Happy!
12                                Lupang Hinirang
13                         Bilady, Bilady, Bilady
14                                   Tiến Quân Ca
15                               Debout Congolais
16                                 İstiklal Marşı
17      Sorood-e Melli-e Jomhouri-e Eslami-e Iran
18                                Deutschlandlied
19                               Phleng Chat Thai
20                             God Save the Queen
21                                La Marseillaise
22                        Il Canto degli Italiani
23                           Mungu ibariki Afrika
24                         Nkosi Sikelel' iAfrika
25                                   Kaba Ma Kyei
26                            Ee Mungu Nguvu Yetu
27                                        Aegukga
28                      ¡Oh, Gloria Inmarcesible!
29                                    Marcha Real
30                      Oh Uganda, Land of Beauty
31                       Himno Nacional Argentino
32                                       Kassaman
33                   Nahnu Djundulla Djundulwatan
34                        Shche ne vmerla Ukrainy
35                                        Mawtini
36                                    Mīlī Surūd
37                           Mazurek Dąbrowskiego
38                                       O Canada
39                          النشيد الوطني المغربي
40                          النشيد الوطني السعودي
41  O'zbekiston Respublikasining Davlat Madhiyasi
42                        Himno Nacional del Perú
43                                  Angola Avante
44                                       Negaraku
45                                   Pátria Amada
46                   God Bless Our Homeland Ghana
47                           النشيد الوطني اليمني
48                          सयौं थुँगा फूलका हामी

In [9]:
csv_1.index

RangeIndex(start=0, stop=49, step=1)

In [11]:
csv_1.columns

Index(['Unnamed: 0', 'Country', 'Population', 'Country Code',
       'National Anthem'],
      dtype='object')

In [14]:
csv_1.describe()

       Unnamed: 0    Population
count    49.00000  4.900000e+01
mean     24.00000  1.374842e+08
std      14.28869  2.734940e+08
min       0.00000  2.913681e+07
25%      12.00000  3.892835e+07
50%      24.00000  5.930869e+07
75%      36.00000  1.095811e+08
max      48.00000  1.439324e+09

In [16]:
csv_1.head(10)

,Unnamed: 0,Country,Population,Country Code,National Anthem
0,0,United States,331002651,US,The Star-Spangled Banner
1,1,China,1439323776,CN,March of the Volunteers
2,2,India,1380004385,IN,Jana Gana Mana
3,3,Brazil,212559417,BR,Hino Nacional Brasileiro
4,4,Pakistan,220892340,PK,Pak Sarzamin Shad Bad
5,5,Indonesia,273523615,ID,Indonesia Raya
6,6,Nigeria,206139589,NG,"Arise, O Compatriots"
7,7,Bangladesh,164689383,BD,Amar Shonar Bangla
8,8,Russia,145934462,RU,State Anthem of the Russian Federation
9,9,Mexico,128932753,MX,Himno Nacional Mexicano

In [17]:
csv_1.tail(4)

,Unnamed: 0,Country,Population,Country Code,National Anthem
45,45,Mozambique,31255435,MZ,Pátria Amada
46,46,Ghana,31072940,GH,God Bless Our Homeland Ghana
47,47,Yemen,29825968,YE,النشيد الوطني اليمني
48,48,Nepal,29136808,NP,सयौं थुँगा फूलका हामी

In [18]:
csv_1[16:21]

,Unnamed: 0,Country,Population,Country Code,National Anthem
16,16,Turkey,84339067,TR,İstiklal Marşı
17,17,Iran,83992949,IR,Sorood-e Melli-e Jomhouri-e Eslami-e Iran
18,18,Germany,83783942,DE,Deutschlandlied
19,19,Thailand,69799978,TH,Phleng Chat Thai
20,20,United Kingdom,67886011,GB,God Save the Queen

In [19]:
print(type(csv_1))

<class 'pandas.core.frame.DataFrame'>

In [20]:
csv_1.to_numpy()

array([[0, 'United States', 331002651, 'US', 'The Star-Spangled Banner'],
       [1, 'China', 1439323776, 'CN', 'March of the Volunteers'],
       [2, 'India', 1380004385, 'IN', 'Jana Gana Mana'],
       [3, 'Brazil', 212559417, 'BR', 'Hino Nacional Brasileiro'],
       [4, 'Pakistan', 220892340, 'PK', 'Pak Sarzamin Shad Bad'],
       [5, 'Indonesia', 273523615, 'ID', 'Indonesia Raya'],
       [6, 'Nigeria', 206139589, 'NG', 'Arise, O Compatriots'],
       [7, 'Bangladesh', 164689383, 'BD', 'Amar Shonar Bangla'],
       [8, 'Russia', 145934462, 'RU',
        'State Anthem of the Russian Federation'],
       [9, 'Mexico', 128932753, 'MX', 'Himno Nacional Mexicano'],
       [10, 'Japan', 126476461, 'JP', 'Kimigayo'],
       [11, 'Ethiopia', 114963588, 'ET', 'Ethiopia, Be Happy!'],
       [12, 'Philippines', 109581078, 'PH', 'Lupang Hinirang'],
       [13, 'Egypt', 102334404, 'EG', 'Bilady, Bilady, Bilady'],
       [14, 'Vietnam', 97338579, 'VN', 'Tiến Quân Ca'],
       [15, 'DR Congo', 89561404, 'CD', 'Debout Congolais'],
       [16, 'Turkey', 84339067, 'TR', 'İstiklal Marşı'],
       [17, 'Iran', 83992949, 'IR',
        'Sorood-e Melli-e Jomhouri-e Eslami-e Iran'],
       [18, 'Germany', 83783942, 'DE', 'Deutschlandlied'],
       [19, 'Thailand', 69799978, 'TH', 'Phleng Chat Thai'],
       [20, 'United Kingdom', 67886011, 'GB', 'God Save the Queen'],
       [21, 'France', 65273511, 'FR', 'La Marseillaise'],
       [22, 'Italy', 60461826, 'IT', 'Il Canto degli Italiani'],
       [23, 'Tanzania', 59734218, 'TZ', 'Mungu ibariki Afrika'],
       [24, 'South Africa', 59308690, 'ZA', "Nkosi Sikelel' iAfrika"],
       [25, 'Myanmar', 54409800, 'MM', 'Kaba Ma Kyei'],
       [26, 'Kenya', 53771296, 'KE', 'Ee Mungu Nguvu Yetu'],
       [27, 'South Korea', 51269185, 'KR', 'Aegukga'],
       [28, 'Colombia', 50882891, 'CO', '¡Oh, Gloria Inmarcesible!'],
       [29, 'Spain', 46754778, 'ES', 'Marcha Real'],
       [30, 'Uganda', 45741007, 'UG', 'Oh Uganda, Land of Beauty'],
       [31, 'Argentina', 45195774, 'AR', 'Himno Nacional Argentino'],
       [32, 'Algeria', 43851044, 'DZ', 'Kassaman'],
       [33, 'Sudan', 43849260, 'SD', 'Nahnu Djundulla Djundulwatan'],
       [34, 'Ukraine', 43733762, 'UA', 'Shche ne vmerla Ukrainy'],
       [35, 'Iraq', 40222493, 'IQ', 'Mawtini'],
       [36, 'Afghanistan', 38928346, 'AF', 'Mīlī Surūd'],
       [37, 'Poland', 37846611, 'PL', 'Mazurek Dąbrowskiego'],
       [38, 'Canada', 37742154, 'CA', 'O Canada'],
       [39, 'Morocco', 36910560, 'MA', 'النشيد الوطني المغربي'],
       [40, 'Saudi Arabia', 34813871, 'SA', 'النشيد الوطني السعودي'],
       [41, 'Uzbekistan', 33469203, 'UZ',
        "O'zbekiston Respublikasining Davlat Madhiyasi"],
       [42, 'Peru', 32971854, 'PE', 'Himno Nacional del Perú'],
       [43, 'Angola', 32866272, 'AO', 'Angola Avante'],
       [44, 'Malaysia', 32365999, 'MY', 'Negaraku'],
       [45, 'Mozambique', 31255435, 'MZ', 'Pátria Amada'],
       [46, 'Ghana', 31072940, 'GH', 'God Bless Our Homeland Ghana'],
       [47, 'Yemen', 29825968, 'YE', 'النشيد الوطني اليمني'],
       [48, 'Nepal', 29136808, 'NP', 'सयौं थुँगा फूलका हामी']],
      dtype=object)

In [22]:
import numpy as np

v=np.asarray(csv_1)
print(v)

[[0 'United States' 331002651 'US' 'The Star-Spangled Banner']
 [1 'China' 1439323776 'CN' 'March of the Volunteers']
 [2 'India' 1380004385 'IN' 'Jana Gana Mana']
 [3 'Brazil' 212559417 'BR' 'Hino Nacional Brasileiro']
 [4 'Pakistan' 220892340 'PK' 'Pak Sarzamin Shad Bad']
 [5 'Indonesia' 273523615 'ID' 'Indonesia Raya']
 [6 'Nigeria' 206139589 'NG' 'Arise, O Compatriots']
 [7 'Bangladesh' 164689383 'BD' 'Amar Shonar Bangla']
 [8 'Russia' 145934462 'RU' 'State Anthem of the Russian Federation']
 [9 'Mexico' 128932753 'MX' 'Himno Nacional Mexicano']
 [10 'Japan' 126476461 'JP' 'Kimigayo']
 [11 'Ethiopia' 114963588 'ET' 'Ethiopia, Be Happy!']
 [12 'Philippines' 109581078 'PH' 'Lupang Hinirang']
 [13 'Egypt' 102334404 'EG' 'Bilady, Bilady, Bilady']
 [14 'Vietnam' 97338579 'VN' 'Tiến Quân Ca']
 [15 'DR Congo' 89561404 'CD' 'Debout Congolais']
 [16 'Turkey' 84339067 'TR' 'İstiklal Marşı']
 [17 'Iran' 83992949 'IR' 'Sorood-e Melli-e Jomhouri-e Eslami-e Iran']
 [18 'Germany' 83783942 'DE' 'Deutschlandlied']
 [19 'Thailand' 69799978 'TH' 'Phleng Chat Thai']
 [20 'United Kingdom' 67886011 'GB' 'God Save the Queen']
 [21 'France' 65273511 'FR' 'La Marseillaise']
 [22 'Italy' 60461826 'IT' 'Il Canto degli Italiani']
 [23 'Tanzania' 59734218 'TZ' 'Mungu ibariki Afrika']
 [24 'South Africa' 59308690 'ZA' "Nkosi Sikelel' iAfrika"]
 [25 'Myanmar' 54409800 'MM' 'Kaba Ma Kyei']
 [26 'Kenya' 53771296 'KE' 'Ee Mungu Nguvu Yetu']
 [27 'South Korea' 51269185 'KR' 'Aegukga']
 [28 'Colombia' 50882891 'CO' '¡Oh, Gloria Inmarcesible!']
 [29 'Spain' 46754778 'ES' 'Marcha Real']
 [30 'Uganda' 45741007 'UG' 'Oh Uganda, Land of Beauty']
 [31 'Argentina' 45195774 'AR' 'Himno Nacional Argentino']
 [32 'Algeria' 43851044 'DZ' 'Kassaman']
 [33 'Sudan' 43849260 'SD' 'Nahnu Djundulla Djundulwatan']
 [34 'Ukraine' 43733762 'UA' 'Shche ne vmerla Ukrainy']
 [35 'Iraq' 40222493 'IQ' 'Mawtini']
 [36 'Afghanistan' 38928346 'AF' 'Mīlī Surūd']
 [37 'Poland' 37846611 'PL' 'Mazurek Dąbrowskiego']
 [38 'Canada' 37742154 'CA' 'O Canada']
 [39 'Morocco' 36910560 'MA' 'النشيد الوطني المغربي']
 [40 'Saudi Arabia' 34813871 'SA' 'النشيد الوطني السعودي']
 [41 'Uzbekistan' 33469203 'UZ'
  "O'zbekiston Respublikasining Davlat Madhiyasi"]
 [42 'Peru' 32971854 'PE' 'Himno Nacional del Perú']
 [43 'Angola' 32866272 'AO' 'Angola Avante']
 [44 'Malaysia' 32365999 'MY' 'Negaraku']
 [45 'Mozambique' 31255435 'MZ' 'Pátria Amada']
 [46 'Ghana' 31072940 'GH' 'God Bless Our Homeland Ghana']
 [47 'Yemen' 29825968 'YE' 'النشيد الوطني اليمني']
 [48 'Nepal' 29136808 'NP' 'सयौं थुँगा फूलका हामी']]

In [23]:
csv_1.sort_index(axis=0,ascending=False)

,Unnamed: 0,Country,Population,Country Code,National Anthem
48,48,Nepal,29136808,NP,सयौं थुँगा फूलका हामी
47,47,Yemen,29825968,YE,النشيد الوطني اليمني
46,46,Ghana,31072940,GH,God Bless Our Homeland Ghana
45,45,Mozambique,31255435,MZ,Pátria Amada
44,44,Malaysia,32365999,MY,Negaraku
43,43,Angola,32866272,AO,Angola Avante
42,42,Peru,32971854,PE,Himno Nacional del Perú
41,41,Uzbekistan,33469203,UZ,O'zbekiston Respublikasining Davlat Madhiyasi
40,40,Saudi Arabia,34813871,SA,النشيد الوطني السعودي
39,39,Morocco,36910560,MA,النشيد الوطني المغربي
38,38,Canada,37742154,CA,O Canada
37,37,Poland,37846611,PL,Mazurek Dąbrowskiego
36,36,Afghanistan,38928346,AF,Mīlī Surūd
35,35,Iraq,40222493,IQ,Mawtini
34,34,Ukraine,43733762,UA,Shche ne vmerla Ukrainy
33,33,Sudan,43849260,SD,Nahnu Djundulla Djundulwatan
32,32,Algeria,43851044,DZ,Kassaman
31,31,Argentina,45195774,AR,Himno Nacional Argentino
30,30,Uganda,45741007,UG,"Oh Uganda, Land of Beauty"
29,29,Spain,46754778,ES,Marcha Real
28,28,Colombia,50882891,CO,"¡Oh, Gloria Inmarcesible!"
27,27,South Korea,51269185,KR,Aegukga
26,26,Kenya,53771296,KE,Ee Mungu Nguvu Yetu
25,25,Myanmar,54409800,MM,Kaba Ma Kyei
24,24,South Africa,59308690,ZA,Nkosi Sikelel' iAfrika
23,23,Tanzania,59734218,TZ,Mungu ibariki Afrika
22,22,Italy,60461826,IT,Il Canto degli Italiani
21,21,France,65273511,FR,La Marseillaise
20,20,United Kingdom,67886011,GB,God Save the Queen
19,19,Thailand,69799978,TH,Phleng Chat Thai
18,18,Germany,83783942,DE,Deutschlandlied
17,17,Iran,83992949,IR,Sorood-e Melli-e Jomhouri-e Eslami-e Iran
16,16,Turkey,84339067,TR,İstiklal Marşı
15,15,DR Congo,89561404,CD,Debout Congolais
14,14,Vietnam,97338579,VN,Tiến Quân Ca
13,13,Egypt,102334404,EG,"Bilady, Bilady, Bilady"
12,12,Philippines,109581078,PH,Lupang Hinirang
11,11,Ethiopia,114963588,ET,"Ethiopia, Be Happy!"
10,10,Japan,126476461,JP,Kimigayo
9,9,Mexico,128932753,MX,Himno Nacional Mexicano
8,8,Russia,145934462,RU,State Anthem of the Russian Federation
7,7,Bangladesh,164689383,BD,Amar Shonar Bangla
6,6,Nigeria,206139589,NG,"Arise, O Compatriots"
5,5,Indonesia,273523615,ID,Indonesia Raya
4,4,Pakistan,220892340,PK,Pak Sarzamin Shad Bad
3,3,Brazil,212559417,BR,Hino Nacional Brasileiro
2,2,India,1380004385,IN,Jana Gana Mana
1,1,China,1439323776,CN,March of the Volunteers
0,0,United States,331002651,US,The Star-Spangled Banner

In [25]:
csv_1['Population'][3]=866923
print(csv_1)

    Unnamed: 0         Country  Population Country Code  \
0            0   United States   331002651           US
1            1           China  1439323776           CN
2            2           India  1380004385           IN
3            3          Brazil      866923           BR
4            4        Pakistan   220892340           PK
5            5       Indonesia   273523615           ID
6            6         Nigeria   206139589           NG
7            7      Bangladesh   164689383           BD
8            8          Russia   145934462           RU
9            9          Mexico   128932753           MX
10          10           Japan   126476461           JP
11          11        Ethiopia   114963588           ET
12          12     Philippines   109581078           PH
13          13           Egypt   102334404           EG
14          14         Vietnam    97338579           VN
15          15        DR Congo    89561404           CD
16          16          Turkey    84339067           TR
17          17            Iran    83992949           IR
18          18         Germany    83783942           DE
19          19        Thailand    69799978           TH
20          20  United Kingdom    67886011           GB
21          21          France    65273511           FR
22          22           Italy    60461826           IT
23          23        Tanzania    59734218           TZ
24          24    South Africa    59308690           ZA
25          25         Myanmar    54409800           MM
26          26           Kenya    53771296           KE
27          27     South Korea    51269185           KR
28          28        Colombia    50882891           CO
29          29           Spain    46754778           ES
30          30          Uganda    45741007           UG
31          31       Argentina    45195774           AR
32          32         Algeria    43851044           DZ
33          33           Sudan    43849260           SD
34          34         Ukraine    43733762           UA
35          35            Iraq    40222493           IQ
36          36     Afghanistan    38928346           AF
37          37          Poland    37846611           PL
38          38          Canada    37742154           CA
39          39         Morocco    36910560           MA
40          40    Saudi Arabia    34813871           SA
41          41      Uzbekistan    33469203           UZ
42          42            Peru    32971854           PE
43          43          Angola    32866272           AO
44          44        Malaysia    32365999           MY
45          45      Mozambique    31255435           MZ
46          46           Ghana    31072940           GH
47          47           Yemen    29825968           YE
48          48           Nepal    29136808           NP

                                  National Anthem
0                        The Star-Spangled Banner
1                         March of the Volunteers
2                                  Jana Gana Mana
3                        Hino Nacional Brasileiro
4                           Pak Sarzamin Shad Bad
5                                  Indonesia Raya
6                            Arise, O Compatriots
7                              Amar Shonar Bangla
8          State Anthem of the Russian Federation
9                         Himno Nacional Mexicano
10                                       Kimigayo
11                            Ethiopia, Be Happy!
12                                Lupang Hinirang
13                         Bilady, Bilady, Bilady
14                                   Tiến Quân Ca
15                               Debout Congolais
16                                 İstiklal Marşı
17      Sorood-e Melli-e Jomhouri-e Eslami-e Iran
18                                Deutschlandlied
19                               Phleng Chat Thai
20                             God Save the Queen
21                                La Marseillaise
22                        Il Canto degli Italiani
23                           Mungu ibariki Afrika
24                         Nkosi Sikelel' iAfrika
25                                   Kaba Ma Kyei
26                            Ee Mungu Nguvu Yetu
27                                        Aegukga
28                      ¡Oh, Gloria Inmarcesible!
29                                    Marcha Real
30                      Oh Uganda, Land of Beauty
31                       Himno Nacional Argentino
32                                       Kassaman
33                   Nahnu Djundulla Djundulwatan
34                        Shche ne vmerla Ukrainy
35                                        Mawtini
36                                    Mīlī Surūd
37                           Mazurek Dąbrowskiego
38                                       O Canada
39                          النشيد الوطني المغربي
40                          النشيد الوطني السعودي
41  O'zbekiston Respublikasining Davlat Madhiyasi
42                        Himno Nacional del Perú
43                                  Angola Avante
44                                       Negaraku
45                                   Pátria Amada
46                   God Bless Our Homeland Ghana
47                           النشيد الوطني اليمني
48                          सयौं थुँगा फूलका हामी

C:\Users\Revan\AppData\Local\Temp\ipykernel_8680\734571810.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv_1['Population'][3]=866923

In [33]:
csv_1.loc[10,"Population"]=1264764628
print(csv_1.iloc[10])

Unnamed: 0                 10
Country                 Japan
Population         1264764628
Country Code               JP
National Anthem      Kimigayo
Name: 10, dtype: object

In [35]:
csv_1.loc[[10],["Population"]]

    Population
10  1264764628

In [36]:
csv_1.drop("Unnamed: 0",axis=1)

,Country,Population,Country Code,National Anthem
0,United States,331002651,US,The Star-Spangled Banner
1,China,1439323776,CN,March of the Volunteers
2,India,1380004385,IN,Jana Gana Mana
3,Brazil,866923,BR,Hino Nacional Brasileiro
4,Pakistan,220892340,PK,Pak Sarzamin Shad Bad
5,Indonesia,273523615,ID,Indonesia Raya
6,Nigeria,206139589,NG,"Arise, O Compatriots"
7,Bangladesh,164689383,BD,Amar Shonar Bangla
8,Russia,145934462,RU,State Anthem of the Russian Federation
9,Mexico,128932753,MX,Himno Nacional Mexicano
10,Japan,1264764628,JP,Kimigayo
11,Ethiopia,114963588,ET,"Ethiopia, Be Happy!"
12,Philippines,109581078,PH,Lupang Hinirang
13,Egypt,102334404,EG,"Bilady, Bilady, Bilady"
14,Vietnam,97338579,VN,Tiến Quân Ca
15,DR Congo,89561404,CD,Debout Congolais
16,Turkey,84339067,TR,İstiklal Marşı
17,Iran,83992949,IR,Sorood-e Melli-e Jomhouri-e Eslami-e Iran
18,Germany,83783942,DE,Deutschlandlied
19,Thailand,69799978,TH,Phleng Chat Thai
20,United Kingdom,67886011,GB,God Save the Queen
21,France,65273511,FR,La Marseillaise
22,Italy,60461826,IT,Il Canto degli Italiani
23,Tanzania,59734218,TZ,Mungu ibariki Afrika
24,South Africa,59308690,ZA,Nkosi Sikelel' iAfrika
25,Myanmar,54409800,MM,Kaba Ma Kyei
26,Kenya,53771296,KE,Ee Mungu Nguvu Yetu
27,South Korea,51269185,KR,Aegukga
28,Colombia,50882891,CO,"¡Oh, Gloria Inmarcesible!"
29,Spain,46754778,ES,Marcha Real
30,Uganda,45741007,UG,"Oh Uganda, Land of Beauty"
31,Argentina,45195774,AR,Himno Nacional Argentino
32,Algeria,43851044,DZ,Kassaman
33,Sudan,43849260,SD,Nahnu Djundulla Djundulwatan
34,Ukraine,43733762,UA,Shche ne vmerla Ukrainy
35,Iraq,40222493,IQ,Mawtini
36,Afghanistan,38928346,AF,Mīlī Surūd
37,Poland,37846611,PL,Mazurek Dąbrowskiego
38,Canada,37742154,CA,O Canada
39,Morocco,36910560,MA,النشيد الوطني المغربي
40,Saudi Arabia,34813871,SA,النشيد الوطني السعودي
41,Uzbekistan,33469203,UZ,O'zbekiston Respublikasining Davlat Madhiyasi
42,Peru,32971854,PE,Himno Nacional del Perú
43,Angola,32866272,AO,Angola Avante
44,Malaysia,32365999,MY,Negaraku
45,Mozambique,31255435,MZ,Pátria Amada
46,Ghana,31072940,GH,God Bless Our Homeland Ghana
47,Yemen,29825968,YE,النشيد الوطني اليمني
48,Nepal,29136808,NP,सयौं थुँगा फूलका हामी